import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from 'jotai';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Resume Spark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
        <div className="relative ">
          <div className="fixed top-0 right-0 w-[350px] h-[350px] bg-[#FE9415] rounded-full blur-[140px] opacity-40 z-[-1] animate-pulse" />
          <div className="fixed bottom-0 left-0 w-[350px] h-[350px] bg-[#FA332B] rounded-full blur-[140px] opacity-35 z-[-1] animate-pulse" />
          {children}
        </div>
        </Provider>
      </body>
    </html>
  );
}
